### PR TITLE
Removing deprecated projects from RSP and Cospective and updating Ato…

### PR DESCRIPTION
**Pull request by jasoncscott**
I'm removing two deprecated projects and attempting to update 1 that is "owned" by a current RSP employee ("Aton" owned by Vahan Sosoyan) but predates his employment at RSP, and he will continue developing after he leaves RSP.

### CODE REVIEW

**Comment by jmertic** [comment]
Hi @jasoncscott - thanks for these updates!

It looks like the change in removing RSP as a sponsor for Aton left that project with no crunchbase entry. Each project needs a crunchbase entry, could you have one added ( can be a simple as making Vahan Sosoyan his own company ). Let me know if you have any questions or concerns.

**Comment by jasoncscott** [comment]
I can try.  Haven't done tat before, so I'll go try to make a Crunchbase account . . .

**Comment by jasoncscott** [comment]
Okay, I made:
* https://www.crunchbase.com/organization/vahan-sosoyan
and since it seems Twitter has a high priority, here's his:
* https://twitter.com/sosoyan

Do you want me to push a new commit with that?  Or would you rather do it on your end?

**Comment by jmertic** [comment]
Feel free to update yourself in your fork if you are comfortable with that.

**Comment by jasoncscott** [comment]
I've added the info to `landscape.yml`, but I think it's getting confused because I tried to edit `processed_landscape.yml` the first time (forgetting that one is auto-generated).

**Comment by jmertic** [comment]
Yep - it appears so.

I think if you can do the edits on your local machine, probably resolving the conflicts there by accepting all of master's revisions should help. 

```
git checkout --theirs processed_landscape.yml
```

**Pull request merged**
