### PR TITLE
Add QtPyConvert project to Landscape

### PR DESCRIPTION
**Pull request by Ahuge**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

- [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project open source, and does your project have at least 250 GitHub stars?
- [x] Has this project been used in the production of a film or game?
- [x] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
- [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ ] Does your project/product name match the text on the logo?
- [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~10 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by Ahuge** [comment]
I didn't have an icon so I quickly made one in gimp.
It's not a great icon, should I just use text instead?

**Comment by dankohn** [comment]
We could help with the logo except that this project doesn't seem to fit the second sentence here: "Projects must have been used successfully in the production of a film, television program, animated content or other projects within the scope of the ASWF. It also should have been designed specifically for the entertainment industry."

**Comment by Ahuge** [comment]
It was developed at Digital Domain specifically for converting our vfx tooling.
It does happen to have extended uses beyond vfx but was originally used for VFX.

If you don't think it fits, I won't fight it and I can close this

**Comment by dankohn** [comment]
I'm not a subject matter expert. I defer to @jmertic and the AWSF experts.

**Comment by jmertic** [comment]
@lgritz Can you comment?

**Comment by lgritz** [comment]
As a general rule, I'm against listing packages here that aren't developed either by or specifically for studios. Even if they are impactful and widely used. For example, we don't list the Linux kernel or gcc.

Though I wasn't familiar with this package, I see now that it was developed at a VFX studio (DD) and we all use Qt so it's relevant, I'm inclined to cut it some slack. I think if people in VFX/anim outside of DD are using it, I'm inclined to list it. If nobody outside DD has heard of it, maybe not so much.

Can I use this to say that I'm on the fence on the "stars" rule? I think this requires human judgment that cannot be easily codified. I can imagine a package that critically important to every large studio, but the nature of it is that only one person at each facility has the narrow expertise to use it. That's definitely one we want to list, despite having only 10 stars. And another package may have 10000 stars because it's something general purpose and appealing to beginners, but is barely used in any real productions.

**Comment by dankohn** [comment]
The stars rule makes more sense in CNCF where everyone is used to finding things on GitHub and starring them.

**Comment by lgritz** [comment]
I may also be weird in that my own use of stars on GH is more like a bookmark than an endorsement.

**Comment by dankohn** [comment]
I think that's how most people use it, actually. But it is useful to see which projects are being bookmarked for being of potential interest.

**Comment by Ahuge** [comment]
I know people at Zoic, DD, Airbud that are using it firsthand.
I've seen clones into other networks but didn't get official confirmation that they were using it.

I'm cool leaving this up and seeing if anyone states their usage.
Or closing it if you don't feel there is enough usage.

**Comment by jmertic** [comment]
I think we are good to list, and I'll take @lgritz feedback of removing the 'stars' requirement.

@Ahuge can you fix the build issue listed below:

```
1:32:17 PM: No cached entry, and can not fetch: digital-domain Can't resolve stock ticker 0547; please manually add a "stock_ticker" key to landscape.yml or set to null
```

**Comment by jmertic** [comment]
@dankohn @alexcontini Can you help clean up the logo? Looks like the plan is to include this in the landscape.

**Comment by dankohn** [comment]
If this version of your logo looks OK, can you please LGTM

**Comment by dankohn** [comment]
@Ahuge ^

**Comment by Ahuge** [comment]
Thanks @dankohn LGTM

**Pull request merged**
