### PR TITLE
Add "Colour" to "Color Science" sub-category.

### PR DESCRIPTION
**Pull request by KelSolaar**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project open source, and does your project have at least 250 GitHub stars?
* [x] Has this project been used in the production of a film or game?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~10 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

This PR adds [Colour](https://github.com/colour-science/colour) to the landscape of Open Source software used in the Motion Picture Industry.

**Colour** is used in many VFX (and Games) studios to perform scientific computations and process digital imaging data. It is also used by various Fortune 500 companies to validate and refine colour transformation pipelines, e.g. Google with Youtube.

### CODE REVIEW

**Comment by KelSolaar** [comment]
The build seems to unfortunately break:

```javascript
7:52:41 PM: TypeError: Cannot read property 'substring' of undefined
7:52:41 PM:     at substring (/opt/build/repo/node_modules/interactive-landscape/tools/fetchImages.js:154:107)
```

**Comment by dankohn** [comment]
The real error was just above: No city for a crunchbase entry for colour-science at https://www.crunchbase.com/organization/colour-science

**Comment by dankohn** [comment]
Ahh, you're right about the other build error. We're investigating.

**Comment by jmertic** [comment]
@KelSolaar - looks like the issue is around the crunchbase entry...

```
No city for a crunchbase entry for colour-science at https://www.crunchbase.com/organization/colour-science
```

It looks like it's fixed now so maybe a rebuild will get it working. Let me trigger that.

**Comment by dankohn** [comment]
I fixed that issue. There’s a separate issue with the SVG that we’re investigating.

**Comment by jordinl83** [comment]
I see there's an exception being thrown which is not handled well, so this itself ends up throwing a different exception.

Commenting out some of the code, the original exception seems to be:

```
Error in parsing SVG: Unbound namespace prefix: "serif"
```

**Comment by dankohn** [comment]
Great. Could you please improve the exception handling and manually edit the SVG to work.

**Pull request merged**
